config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :users

  # トップページの表示
  root to: 'items#index'
  resources :items do
    resources :orders, only:[:create, :index]
  end
  resources :comments, only:[:create,:update,:destroy] do
    member do
      get 'restore'
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to_active_hash :category
  belongs_to_active_hash :status
  belongs_to_active_hash :shipping_charge
  belongs_to_active_hash :area
  belongs_to_active_hash :shipping_time
  has_one_attached :image
  has_one :order
  has_many :comments, dependent: :destroy


  #空の投稿を保存できないようにする
  validates :image, :name, :description, :category_id, :status_id, :shipping_charge_id, :area_id, :shipping_time_id, :price, presence: true

  #ジャンルの選択が「--」の時は保存できないようにする
  validates :category_id, :status_id, :shipping_charge_id, :area_id, :shipping_time_id, numericality: { other_than: 1 }

  #価格は300円から9999999円の間で設定すること
  validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 },
  #価格は半角数字で入力すること
  format: { with: /\A[0-9]+\z/, message: "Please enter in single-byte number" }

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  before_action :set_item, only: [:edit, :update, :show, :destroy]
  
  def index
    @items = Item.order("id DESC")
    end

  def new
    @item = Item.new
  end
  
  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def show
    @comment = Comment.new
    @commentALL = @item.comments
  end
  

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render :show
    end
  end
  

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end

  end

  private

  def item_params
    params.require(:item).permit(:image,:name,:description,:category_id,:status_id,:shipping_charge_id,:area_id,:shipping_time_id,:price).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.haml
%body
  .items-sell-contents
    %header.items-sell-header
      = link_to image_tag('furima-logo-color.png' , size: '185x50'), "/"
    .items-sell-main
      %h2.items-sell-title 商品の情報を入力
      = form_with model: @item, url: item_path, local: true, method: :patch do |f|
        = render 'shared/error_messages', model: f.object
        .img-upload
          .weight-bold-text
            出品画像
            %span.indispensable 必須
          .click-upload
            %p
              クリックしてファイルをアップロード
            = f.file_field :image, id:"item-image"
        .new-items
          .weight-bold-text
            商品名
            %span.indispensable 必須
          = f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40"
          .items-explain
            .weight-bold-text
              商品の説明
              %span.indispensable 必須
            = f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000"
        .items-detail
          .weight-bold-text 商品の詳細
          .form
            .weight-bold-text
              カテゴリー
              %span.indispensable 必須
            = f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"})
            .weight-bold-text
              商品の状態
              %span.indispensable 必須
            = f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"})
        .items-detail
          .weight-bold-text.question-text
            %span 配送について
            %a.question{:href => "#"} ?
          .form
            .weight-bold-text
              配送料の負担
              %span.indispensable 必須
            = f.collection_select(:shipping_charge_id, ShippingCharge.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"})
            .weight-bold-text
              発送元の地域
              %span.indispensable 必須
            = f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"})
            .weight-bold-text
              発送までの日数
              %span.indispensable 必須
            = f.collection_select(:shipping_time_id, ShippingTime.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"})
        .sell-price
          .weight-bold-text.question-text
            %span
              販売価格
              %br>/
              (¥300〜9,999,999)
            %a.question{:href => "#"} ?
          %div
            .price-content
              .price-text
                %span 価格
                %span.indispensable 必須
              %span.sell-yen ¥
              = f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300"
            .price-content
              %span 販売手数料 (10%)
              %span
                %span#add-tax-price>
                円
            .price-content
              %span 販売利益
              %span
                %span#profit>
                円
        .caution
          %p.sentence
            %a{:href => "#"} 禁止されている出品、
            %a{:href => "#"} 行為
            を必ずご確認ください。
          %p.sentence
            またブランド品でシリアルナンバー等がある場合はご記載ください。
            %a{:href => "#"} 偽ブランドの販売
            は犯罪であり処罰される可能性があります。
          %p.sentence
            また、出品をもちまして
            %a{:href => "#"} 加盟店規約
            に同意したことになります。
        .sell-btn-contents
          = f.submit "変更する" ,class:"sell-btn"
          = link_to 'もどる', root_path, class:"back-btn"
    %footer.items-sell-footer
      %ul.menu
        %li
          %a{:href => "#"} プライバシーポリシー
        %li
          %a{:href => "#"} フリマ利用規約
        %li
          %a{:href => "#"} 特定商取引に関する表記
      = link_to image_tag('furima-logo-color.png' , size: '185x50'), "/"
      %p.inc
        ©︎Furima,Inc.

app/views/items/index.html.haml
= render "shared/header"
.main
  .title-contents
    %h2.service-title
      人生を変えるアプリ
    %p.service-explain
      FURIMAはだれでもかんたんに出品・購入できる
    %p.service-explain
      フリマアプリです
    .store-btn
      = link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#"
      = link_to image_tag("dl-android.png", class:"google-btn"), "#"
  .select-reason-contents
    %h2.title
      FURIMAが選ばれる3つの理由
    %ul.reason-lists
      %li.list
        = image_tag "furima-intro01.png", class:"list-pict"
        %span.reason-list-number 1
        %h3.reason-list-text
          %span.reason-list-blue-text 3分
          ですぐに出品
        %p.reason-list-description
          スマホで入力するだけで簡単に出品できる！
      %li.list
        = image_tag "furima-intro02.png", class:"list-pict"
        %span.reason-list-number 2
        %h3.reason-list-text
          %span.reason-list-blue-text シンプル
          で使いやすい
        %p.reason-list-description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list
        = image_tag "furima-intro03.png", class:"list-pict"
        %span.reason-list-number 3
        %h3.reason-list-text
          手数料
          %span.reason-list-blue-text 業界最安
        %p.reason-list-description
          最大3%でお得に出品&amp;購入！
  .ad-contents
    %h2.ad-title
      会員数日本一位
    %p.ad-explain
      FURIMAは、フリマアプリで最も人気。
    %p.ad-explain
      出品・購入回数も業界最多です！
    %p.ad-explain
      ほしかったあの商品に出会えるかもしれません。
    .store-btn
      = link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#"
      = link_to image_tag("dl-android.png", class:"google-btn"), "#"
  .feature-contents
    %h2.title
      FURIMAの特徴
    %ul.feature-lists
      %li.list
        = image_tag "furima-intro04.png", class:"list-pict"
        %h3.feature-list-text
          簡単に売り買いできる
        %p.feature-list-description
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %li.list
        = image_tag "furima-intro05.png", class:"list-pict"
        %h3.feature-list-text
          売上金は即日振込みに対応
        %p.feature-list-description
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします。
      %li.list
        = image_tag "furima-intro06.png", class:"list-pict"
        %h3.feature-list-text
          様々な支払いに対応
        %p.feature-list-description
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  .item-contents
    %h2.title ピックアップカテゴリー
    = link_to '新規投稿商品', "#", class: "subtitle"
    %ul.item-lists
      - @items.each do |item|
        %li.list
          = link_to item_path(item.id), method: :get do
            .item-img-content{:style => "background-image: url(#{item.image});"}
              = image_tag item.image, class: 'item-image' if item.image.attached?
              - if item.order.present?
                .sold-out
                  %span Sold Out!!
            .item-info
              %h3.item-name
                = item.name
              .item-price
                %span
                  = item.price
                  円
                  %br>/
                  (税込み)
                .star-btn
                  = image_tag "star.png", class:"star-icon"
                  %span.star-count 0
      - if @items.length == 0
        %li.list
          = link_to '#' do
            = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "item-img"
            .item-info
              %h3.item-name
                商品を出品してね！
              .item-price
                %span
                  99999999円
                  %br>/
                  (税込み)
                .star-btn
                  = image_tag "star.png", class:"star-icon"
                  %span.star-count 0
.purchase-btn
  %span.purchase-btn-text 出品する
  = link_to new_item_path do
    = image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon"
= render "shared/footer"
= Rails.application.credentials.basic_auth_user

app/views/items/new.html.haml
%body
  .items-sell-contents
    %header.items-sell-header
      = link_to image_tag('furima-logo-color.png' , size: '185x50'), "/"
    .items-sell-main
      %h2.items-sell-title 商品の情報を入力
      = form_with model: @item, url: items_path, class: 'item-main',local: true do |f|
        = render 'shared/error_messages', model: f.object
        .img-upload
          .weight-bold-text
            出品画像
            %span.indispensable 必須
          .click-upload
            %p
              クリックしてファイルをアップロード
            = f.file_field :image, id:"item-image"
        .new-items
          .weight-bold-text
            商品名
            %span.indispensable 必須
          = f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40"
          .items-explain
            .weight-bold-text
              商品の説明
              %span.indispensable 必須
            = f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000"
        .items-detail
          .weight-bold-text 商品の詳細
          .form
            .weight-bold-text
              カテゴリー
              %span.indispensable 必須
            = f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"})
            .weight-bold-text
              商品の状態
              %span.indispensable 必須
            = f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"})
        .items-detail
          .weight-bold-text.question-text
            %span 配送について
            %a.question{:href => "#"} ?
          .form
            .weight-bold-text
              配送料の負担
              %span.indispensable 必須
            = f.collection_select(:shipping_charge_id, ShippingCharge.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"})
            .weight-bold-text
              発送元の地域
              %span.indispensable 必須
            = f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"})
            .weight-bold-text
              発送までの日数
              %span.indispensable 必須
            = f.collection_select(:shipping_time_id, ShippingTime.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"})
        .sell-price
          .weight-bold-text.question-text
            %span
              販売価格
              %br>/
              (¥300〜9,999,999)
            %a.question{:href => "#"} ?
          %div
            .price-content
              .price-text
                %span 価格
                %span.indispensable 必須
              %span.sell-yen ¥
              = f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300"
            .price-content
              %span 販売手数料 (10%)
              %span
                %span#add-tax-price>
                円
            .price-content
              %span 販売利益
              %span
                %span#profit>
                円
        .caution
          %p.sentence
            %a{:href => "#"} 禁止されている出品、
            %a{:href => "#"} 行為
            を必ずご確認ください。
          %p.sentence
            またブランド品でシリアルナンバー等がある場合はご記載ください。
            %a{:href => "#"} 偽ブランドの販売
            は犯罪であり処罰される可能性があります。
          %p.sentence
            また、出品をもちまして
            %a{:href => "#"} 加盟店規約
            に同意したことになります。
        .sell-btn-contents
          = f.submit "出品する" ,class:"sell-btn"
          = link_to 'もどる', root_path, class:"back-btn"
    %footer.items-sell-footer
      %ul.menu
        %li
          %a{:href => "#"} プライバシーポリシー
        %li
          %a{:href => "#"} フリマ利用規約
        %li
          %a{:href => "#"} 特定商取引に関する表記
      = link_to image_tag('furima-logo-color.png' , size: '185x50'), "/"
      %p.inc
        ©︎Furima,Inc.

app/views/items/show.html.haml
= render "shared/header"
.item-show
  .item-box
    %h2.name
      = @item.name
    .item-img-content
      = image_tag @item.image.variant(resize:'500x500'), class: '@item-image' if @item.image.attached?
      - if @item.order.present?
        .sold-out
          %span Sold Out!!
    .item-price-box
      %span.item-price
        = @item.price
        円
        %br/
      %span.item-postage
        (税込) 送料込み
    - if user_signed_in? && current_user.id == @item.user_id
      = link_to '商品の編集', edit_item_path(@item.id), method: :get, class: "item-red-btn"
      %p.or-text or
      = link_to '削除', item_path(@item.id), method: :delete, class:'item-destroy'
    - elsif @item.order == nil
      = link_to '購入画面に進む', item_orders_path(@item), method: :get, class:"item-red-btn"
    .item-explain-box
      %span= "商品説明"
    %table.detail-table
      %tbody
        %tr
          %th.detail-item 出品者
          %td.detail-value= @item.user.nickname
        %tr
          %th.detail-item カテゴリー
          %td.detail-value= @item.category.name
        %tr
          %th.detail-item 商品の状態
          %td.detail-value= @item.status.name
        %tr
          %th.detail-item 配送料の負担
          %td.detail-value= @item.shipping_charge.name
        %tr
          %th.detail-item 発送元の地域
          %td.detail-value= @item.area.name
        %tr
          %th.detail-item 発送日の目安
          %td.detail-value= @item.shipping_time.name
    .option
      .favorite-btn
        = image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"
        %span お気に入り 0
      .report-btn
        = image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"
        %span 不適切な商品の通報
  .comment-box
    .comment_list
    
      - if user_signed_in?
        - @commentALL.each do |comment|
          - if comment.user_id == current_user.id
            -#   ===================================
            -#   コメントユーザーとログインユーザーが同一の場合
            -#   ===================================
            .comment_Me.comment_one_block{data:{index: comment.id}}
              - if comment.delete_check == 1   # 削除済の場合
                .comment_content
                  = render 'items/template_comment/comment_delete_restore_btn',comment: comment
              - else   # 削除されていない場合
                .comment_content
                  = comment.comment
                  .comment_create_at
                    = comment.created_at.strftime("%Y年%m月%d日 %H時%M分")
                  - if comment.item.user.id == current_user.id
                    .comment_delete.me_pre_delete{data:{index: comment.id}}
                      = link_to '削除する', comment_path(comment.id) ,method: :patch
              = render 'items/template_comment/comment_name',comment: comment
          - else 
            -#   ===================================
            -#   コメントユーザーとログインユーザーが異なる場合の場合
            -#   ===================================
            .comment_Other.comment_one_block{data:{index: comment.id}}
              = render 'items/template_comment/comment_name',comment: comment
              - if comment.delete_check == 1   # 削除済の場合
                .comment_content_other
                  出品者によりこのコメントは削除されました。
                  = render 'items/template_comment/comment_delete_restore_btn',comment: comment
              - else    # 削除されていない場合
                .comment_content_other
                  = comment.comment
                  .comment_create_at
                    = comment.created_at.strftime("%Y年%m月%d日 %H時%M分")
                  - if comment.item.user.id == current_user   # 出品者とログインユーザーが等しい場合
                    .comment_delete.other_pre_delete{data:{index: comment.id}}
                      = link_to '削除する', comment_path(comment.id) ,method: :patch
                              
    -#   ===================================
    -#   投稿フォーム
    -#   ===================================
    - if user_signed_in?
      = form_with model:@comment ,class:"comment-box", local: true do |f|
        = f.text_area :comment,id: "comment_body",class: "comment-text"
        = f.hidden_field :item_id, value: @item.id

        %p.comment-warn
          相手のことを考え丁寧なコメントを心がけましょう。
          %br/
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %button.comment-btn{:type => "submit"}
          = image_tag "comment.png" ,class:"comment-flag,comment-flag-icon",width:"20",height:"20"
          %span
            コメントする
            %span
  .links
    %a.change-item-btn{:href => "#"}
      ＜ 前の商品
    %a.change-item-btn{:href => "#"}
      後ろの商品 ＞
  %a.another-item{:href => "#"}
    = @item.category.name
    をもっと見る
= render "shared/footer"